"""
Author: Wenhua Yang
Date: 09/18/2016

A typical authorization api for external use(tests code). Used for granting
the the authority of further resources visiting, e.g. use search api requires
a token generated by this auth_api.
"""

from flask import Flask, Response
import json

from auth_api.provider import auth_service


app = Flask(__name__)


@app.route("/token/<client_id>/<secret>")
def get_token(client_id, secret):
    ret_json = json.dumps(auth_service.get_token(client_id, secret))
    return Response(ret_json, mimetype='application/json')
